title: sarahis.cool
short_title: sarahhiebl
description: Sarah is cool
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
