---
title: Heart of Gold
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
short_title: hog
description: Web Graphic Novel Heart of Gold by Eli Baum and Viv Tanner
baseurl: 
permalink: "/:path/"
gems:
- jekyll-menus
- jekyll-feed
- jekyll-archives
