title: Heart of Gold
short_title: hog
description: Web Graphic Novel Heart of Gold by Eli Baum and Viv Tanner
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
