---
title: Heart of Gold
short_title: HOG
description: A web graphic novel by Eli Baum and Viv Tanner
baseurl: 
permalink: "/comic/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: page
collections:
  projects:
    output: true
    permalink: "/projects/:path/"
gems:
- jekyll-menus
- jekyll-feed
- jekyll-archives
timezone: Etc/UTC
