---
---

---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
  - landing-page
- type: directory
  path: _projects
  label: Comic Pages
  create: all
  match: "*"
  templates:
  - project
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
