---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Page Nummer
- name: visible_title
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Sichtbarer Titel
- type: textarea
  name: beschreibung
  label: Beschreibung
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: date
  type: datetime
  label: Veröffentlichungsdatum
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: boolean
  name: doublepage
  label: Doppelseite
- type: boolean
  name: chapter
  label: Ist ein Chapter?
- name: chapter_bg
  type: file
  config:
    maxSize: 250
  label: Chapter Bild
  description: Falls Chapter dann Hintergrundbild
  showOnly:
    field: chapter
    value: true
- name: banner_image
  label: Bild
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
pages:
- _projects/page-37.html
- _projects/page-43.html
- _projects/page-42.html
- _projects/page-17.html
- _projects/page-41.html
- _projects/page-01.html
- _projects/page-38.html
- _projects/page-40.html
- _projects/page-39.html
- _projects/page-34.html
- _projects/page-36.html
- _projects/page-35.html
- _projects/page-30.html
- _projects/page-32-33.html
- _projects/page-31.html
- _projects/page-27.html
- _projects/page-29.html
- _projects/page-28.html
- _projects/page-25.html
- _projects/page-26.html
- _projects/page-24.html
- _projects/page-23.html
- _projects/page-22.html
- _projects/page-21.html
- _projects/page-20.html
- _projects/page-19.html
- _projects/page-18.html
- _projects/page-15.html
- _projects/page-16.html
- _projects/page-14.html
- _projects/page-13.html
- _projects/page-11.html
- _projects/page-9.html
- _projects/page-12.html
- _projects/page-10.html
- _projects/page-7.html
- _projects/page-8.html
- _projects/page-5.html
- _projects/page-6.html
- _projects/page-4.html
- _projects/page-3.html
- _projects/page-2.html
