---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Page Nummer
- name: visible_title
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Sichtbarer Titel
- type: textarea
  name: beschreibung
  label: Beschreibung
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: date
  type: datetime
  label: Veröffentlichungsdatum
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: boolean
  name: doublepage
  label: Doppelseite
- type: boolean
  name: chapter
  label: Ist ein Chapter?
- name: chapter_bg
  type: file
  config:
    maxSize: 250
  label: Chapter Bild
  description: Falls Chapter dann Hintergrundbild
  showOnly:
    field: chapter
    value: true
- name: banner_image
  label: Bild
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
pages:
- _projects/159.html
- _projects/page-01.html
- _projects/page-10.html
- _projects/page-100.html
- _projects/page-101.html
- _projects/page-102.html
- _projects/page-103.html
- _projects/page-104.html
- _projects/page-105.html
- _projects/page-106-107.html
- _projects/page-108.html
- _projects/page-109.html
- _projects/page-11.html
- _projects/page-110.html
- _projects/page-111.html
- _projects/page-112.html
- _projects/page-113.html
- _projects/page-114.html
- _projects/page-115.html
- _projects/page-116.html
- _projects/page-117.html
- _projects/page-118.html
- _projects/page-119.html
- _projects/page-12.html
- _projects/page-120.html
- _projects/page-121.html
- _projects/page-122.html
- _projects/page-123.html
- _projects/page-124.html
- _projects/page-125.html
- _projects/page-126.html
- _projects/page-127.html
- _projects/page-128.html
- _projects/page-129.html
- _projects/page-13.html
- _projects/page-130.html
- _projects/page-131.html
- _projects/page-132.html
- _projects/page-133.html
- _projects/page-134.html
- _projects/page-135.html
- _projects/page-136.html
- _projects/page-137.html
- _projects/page-138.html
- _projects/page-139.html
- _projects/page-14.html
- _projects/page-140.html
- _projects/page-141.html
- _projects/page-142.html
- _projects/page-143.html
- _projects/page-144.html
- _projects/page-145.html
- _projects/page-146.html
- _projects/page-147.html
- _projects/page-148.html
- _projects/page-149.html
- _projects/page-15.html
- _projects/page-150.html
- _projects/page-151.html
- _projects/page-152.html
- _projects/page-153.html
- _projects/page-154.html
- _projects/page-155.html
- _projects/page-156.html
- _projects/page-157.html
- _projects/page-158.html
- _projects/page-16.html
- _projects/page-160.html
- _projects/page-161.html
- _projects/page-162.html
- _projects/page-163.html
- _projects/page-17.html
- _projects/page-176.html
- _projects/page-177.html
- _projects/page-178.html
- _projects/page-179.html
- _projects/page-18.html
- _projects/page-180.html
- _projects/page-181.html
- _projects/page-182.html
- _projects/page-183.html
- _projects/page-184.html
- _projects/page-185.html
- _projects/page-187-188.html
- _projects/page-189.html
- _projects/page-19.html
- _projects/page-190.html
- _projects/page-191.html
- _projects/page-192.html
- _projects/page-193.html
- _projects/page-194.html
- _projects/page-195.html
- _projects/page-196.html
- _projects/page-197.html
- _projects/page-198.html
- _projects/page-199.html
- _projects/page-2.html
- _projects/page-20.html
- _projects/page-200.html
- _projects/page-201.html
- _projects/page-202.html
- _projects/page-203.html
- _projects/page-204.html
- _projects/page-205.html
- _projects/page-206.html
- _projects/page-207.html
- _projects/page-208.html
- _projects/page-209.html
- _projects/page-21.html
- _projects/page-210.html
- _projects/page-211.html
- _projects/page-212.html
- _projects/page-213.html
- _projects/page-214.html
- _projects/page-215.html
- _projects/page-216.html
- _projects/page-217.html
- _projects/page-218.html
- _projects/page-219.html
- _projects/page-22.html
- _projects/page-220.html
- _projects/page-221.html
- _projects/page-222.html
- _projects/page-223.html
- _projects/page-224.html
- _projects/page-225.html
- _projects/page-226.html
- _projects/page-227.html
- _projects/page-228.html
- _projects/page-229.html
- _projects/page-23.html
- _projects/page-230.html
- _projects/page-231.html
- _projects/page-232.html
- _projects/page-233.html
- _projects/page-234.html
- _projects/page-235_236.html
- _projects/page-237.html
- _projects/page-238-1.html
- _projects/page-238.html
- _projects/page-24.html
- _projects/page-240.html
- _projects/page-241.html
- _projects/page-242.html
- _projects/page-243.html
- _projects/page-244.html
- _projects/page-245.html
- _projects/page-246.html
- _projects/page-247-1.html
- _projects/page-247.html
- _projects/page-249.html
- _projects/page-25.html
- _projects/page-250.html
- _projects/page-251.html
- _projects/page-252.html
- _projects/page-253.html
- _projects/page-254.html
- _projects/page-255.html
- _projects/page-256.html
- _projects/page-257.html
- _projects/page-258.html
- _projects/page-259.html
- _projects/page-26.html
- _projects/page-260.html
- _projects/page-261.html
- _projects/page-262.html
- _projects/page-263.html
- _projects/page-264.html
- _projects/page-265.html
- _projects/page-266.html
- _projects/page-267.html
- _projects/page-268.html
- _projects/page-269.html
- _projects/page-27.html
- _projects/page-270.html
- _projects/page-271.html
- _projects/page-272.html
- _projects/page-273.html
- _projects/page-274.html
- _projects/page-275.html
- _projects/page-276.html
- _projects/page-277.html
- _projects/page-278.html
- _projects/page-279.html
- _projects/page-28.html
- _projects/page-280.html
- _projects/page-281.html
- _projects/page-283.html
- _projects/page-284.html
- _projects/page-285.html
- _projects/page-286.html
- _projects/page-287.html
- _projects/page-288.html
- _projects/page-289.html
- _projects/page-29.html
- _projects/page-290.html
- _projects/page-291.html
- _projects/page-292.html
- _projects/page-293.html
- _projects/page-294.html
- _projects/page-295.html
- _projects/page-296.html
- _projects/page-297.html
- _projects/page-298.html
- _projects/page-299.html
- _projects/page-3.html
- _projects/page-30.html
- _projects/page-300.html
- _projects/page-301-1.html
- _projects/page-301.html
- _projects/page-303.html
- _projects/page-304.html
- _projects/page-305.html
- _projects/page-306.html
- _projects/page-307.html
- _projects/page-308.html
- _projects/page-309.html
- _projects/page-31.html
- _projects/page-310.html
- _projects/page-311.html
- _projects/page-312.html
- _projects/page-313.html
- _projects/page-314.html
- _projects/page-315.html
- _projects/page-316.html
- _projects/page-317.html
- _projects/page-318.html
- _projects/page-319.html
- _projects/page-32-33.html
- _projects/page-320.html
- _projects/page-321.html
- _projects/page-322.html
- _projects/page-323-1.html
- _projects/page-323.html
- _projects/page-325.html
- _projects/page-326.html
- _projects/page-327.html
- _projects/page-328.html
- _projects/page-329.html
- _projects/page-330.html
- _projects/page-331.html
- _projects/page-332.html
- _projects/page-333.html
- _projects/page-334.html
- _projects/page-335.html
- _projects/page-34.html
- _projects/page-35.html
- _projects/page-36.html
- _projects/page-37.html
- _projects/page-38.html
- _projects/page-39.html
- _projects/page-4.html
- _projects/page-40.html
- _projects/page-41.html
- _projects/page-42.html
- _projects/page-43.html
- _projects/page-44.html
- _projects/page-45.html
- _projects/page-46.html
- _projects/page-47.html
- _projects/page-48.html
- _projects/page-49.html
- _projects/page-5.html
- _projects/page-50.html
- _projects/page-51.html
- _projects/page-52.html
- _projects/page-53.html
- _projects/page-54.html
- _projects/page-55.html
- _projects/page-56.html
- _projects/page-57.html
- _projects/page-58.html
- _projects/page-59.html
- _projects/page-6.html
- _projects/page-60.html
- _projects/page-61.html
- _projects/page-62.html
- _projects/page-63.html
- _projects/page-64.html
- _projects/page-65.html
- _projects/page-66.html
- _projects/page-67.html
- _projects/page-68.html
- _projects/page-69.html
- _projects/page-7.html
- _projects/page-70.html
- _projects/page-71.html
- _projects/page-72.html
- _projects/page-73.html
- _projects/page-74.html
- _projects/page-75.html
- _projects/page-76.html
- _projects/page-77.html
- _projects/page-78.html
- _projects/page-79.html
- _projects/page-8.html
- _projects/page-80.html
- _projects/page-81.html
- _projects/page-82.html
- _projects/page-83.html
- _projects/page-84.html
- _projects/page-85.html
- _projects/page-86.html
- _projects/page-87.html
- _projects/page-88.html
- _projects/page-89.html
- _projects/page-9.html
- _projects/page-90.html
- _projects/page-91.html
- _projects/page-92.html
- _projects/page-93.html
- _projects/page-94.html
- _projects/page-95.html
- _projects/page-96-97.html
- _projects/page-98.html
- _projects/page-99.html
