---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Page Nummer
- name: visible_title
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Sichtbarer Titel
- type: textarea
  name: beschreibung
  label: Beschreibung
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: date
  type: datetime
  label: Veröffentlichungsdatum
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: boolean
  name: doublepage
  label: Doppelseite
- type: boolean
  name: chapter
  label: Ist ein Chapter?
- name: chapter_bg
  type: file
  config:
    maxSize: 250
  label: Chapter Bild
  description: Falls Chapter dann Hintergrundbild
  showOnly:
    field: chapter
    value: true
- name: banner_image
  label: Bild
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
pages:
- _projects/page-181.html
- _projects/page-180.html
- _projects/page-179.html
- _projects/page-178.html
- _projects/page-177.html
- _projects/page-176.html
- _projects/page-24.html
- _projects/page-151.html
- _projects/page-42.html
- _projects/page-158.html
- _projects/page-85.html
- _projects/page-14.html
- _projects/page-83.html
- _projects/page-127.html
- _projects/page-43.html
- _projects/page-101.html
- _projects/page-96-97.html
- _projects/page-111.html
- _projects/page-57.html
- _projects/page-154.html
- _projects/page-26.html
- _projects/page-115.html
- _projects/page-60.html
- _projects/page-9.html
- _projects/page-6.html
- _projects/page-22.html
- _projects/page-121.html
- _projects/page-125.html
- _projects/page-112.html
- _projects/page-95.html
- _projects/page-10.html
- _projects/page-71.html
- _projects/page-84.html
- _projects/page-65.html
- _projects/page-131.html
- _projects/page-49.html
- _projects/page-21.html
- _projects/page-155.html
- _projects/page-5.html
- _projects/page-3.html
- _projects/page-105.html
- _projects/page-34.html
- _projects/page-18.html
- _projects/page-15.html
- _projects/page-50.html
- _projects/page-80.html
- _projects/page-161.html
- _projects/page-79.html
- _projects/page-7.html
- _projects/page-162.html
- _projects/page-23.html
- _projects/page-94.html
- _projects/page-2.html
- _projects/page-56.html
- _projects/page-134.html
- _projects/page-99.html
- _projects/page-122.html
- _projects/page-63.html
- _projects/page-108.html
- _projects/page-133.html
- _projects/page-13.html
- _projects/page-40.html
- _projects/page-76.html
- _projects/page-102.html
- _projects/page-69.html
- _projects/page-117.html
- _projects/page-70.html
- _projects/page-114.html
- _projects/page-28.html
- _projects/page-30.html
- _projects/page-38.html
- _projects/page-129.html
- _projects/page-53.html
- _projects/page-119.html
- _projects/page-47.html
- _projects/page-157.html
- _projects/page-11.html
- _projects/page-55.html
- _projects/page-01.html
- _projects/page-31.html
- _projects/page-46.html
- _projects/page-139.html
- _projects/page-72.html
- _projects/page-148.html
- _projects/page-145.html
- _projects/page-32-33.html
- _projects/page-140.html
- _projects/page-126.html
- _projects/page-61.html
- _projects/page-93.html
- _projects/page-36.html
- _projects/page-58.html
- _projects/page-59.html
- _projects/page-78.html
- _projects/page-90.html
- _projects/page-35.html
- _projects/page-27.html
- _projects/page-17.html
- _projects/page-29.html
- _projects/page-141.html
- _projects/page-75.html
- _projects/page-147.html
- _projects/page-123.html
- _projects/page-113.html
- _projects/page-120.html
- _projects/page-16.html
- _projects/page-124.html
- _projects/page-110.html
- _projects/page-4.html
- _projects/page-98.html
- _projects/page-106-107.html
- _projects/page-86.html
- _projects/page-88.html
- _projects/page-81.html
- _projects/page-153.html
- _projects/page-68.html
- _projects/page-138.html
- _projects/page-89.html
- _projects/page-25.html
- _projects/page-8.html
- _projects/page-64.html
- _projects/page-12.html
- _projects/page-156.html
- _projects/page-87.html
- _projects/page-146.html
- _projects/page-91.html
- _projects/page-163.html
- _projects/page-51.html
- _projects/page-73.html
- _projects/page-116.html
- _projects/page-54.html
- _projects/page-128.html
- _projects/page-48.html
- _projects/page-66.html
- _projects/page-160.html
- _projects/page-82.html
- _projects/page-44.html
- _projects/page-45.html
- _projects/page-41.html
- _projects/page-132.html
- _projects/page-150.html
- _projects/page-100.html
- _projects/page-136.html
- _projects/page-149.html
- _projects/page-118.html
- _projects/page-109.html
- _projects/page-144.html
- _projects/page-130.html
- _projects/page-135.html
- _projects/159.html
- _projects/page-92.html
- _projects/page-103.html
- _projects/page-62.html
- _projects/page-37.html
- _projects/page-143.html
- _projects/page-77.html
- _projects/page-137.html
- _projects/page-104.html
- _projects/page-19.html
- _projects/page-67.html
- _projects/page-52.html
- _projects/page-74.html
- _projects/page-152.html
- _projects/page-142.html
- _projects/page-20.html
- _projects/page-39.html
